/**
 * Change-impact routing.
 *
 * Answers one question: given a set of changed paths, which validation units
 * could possibly be affected? The bias is deliberately one-directional.
 *
 *   The classifier is allowed to waste runner time. It is not allowed to hide a
 *   real regression. Anything it cannot classify resolves to "run everything",
 *   and a unit omitted from the manifest's domain list simply runs more often
 *   than it needs to.
 *
 * This logic lives here, in repository-owned code, rather than in GitHub path
 * filters, so that it can be unit tested. `tools/validation/validation-arch.ts`
 * tests both directions: that a contracts change reaches the widest validation,
 * and that an unknown path reaches *all* of it.
 */

// --- Path classification -----------------------------------------------------

/** How a single changed path was understood. */
export type PathVerdict =
  /** Maps to a repository domain; see `Domain` in manifest.ts. */
  | { readonly kind: "domain"; readonly domain: string }
  /** Generated output or VCS metadata. Cannot change behaviour. */
  | { readonly kind: "generated" }
  /** Not understood. Forces the full validation set. */
  | { readonly kind: "unknown" };

/** Normalise a git path: strip `./`, quotes, and a leading `/`. */
const clean = (p: string): string => p.replace(/^\.\//, "").replace(/^["']|["']$/g, "").replace(/^\//, "");

/**
 * Ordered rules, most specific first. The first match wins, so a generated
 * subdirectory must be listed before the directory that contains it.
 */
const RULES: ReadonlyArray<{ readonly test: RegExp; readonly verdict: PathVerdict }> = [
  // --- Generated output and VCS metadata: cannot change behaviour ----------
  { test: /^(node_modules|dist|\.git)\//, verdict: { kind: "generated" } },
  { test: /^apps\/[^/]+\/dist\//, verdict: { kind: "generated" } },
  { test: /^packages\/[^/]+\/dist\//, verdict: { kind: "generated" } },
  // Capacitor copies the web bundle here; it is output, not native source.
  { test: /^apps\/explorer\/android\/app\/src\/main\/assets\//, verdict: { kind: "generated" } },
  { test: /^apps\/explorer\/android\/(\.gradle|app\/build)\//, verdict: { kind: "generated" } },
  { test: /^apps\/explorer\/android\/local\.properties$/, verdict: { kind: "generated" } },
  // Visual evidence is regenerated by the capture jobs, never hand-edited.
  { test: /^testdata\/(visual|pixi-spike)\//, verdict: { kind: "generated" } },
  { test: /(^|\/)\.DS_Store$/, verdict: { kind: "generated" } },
  { test: /\.log$/, verdict: { kind: "generated" } },

  // --- The measuring apparatus: always everything --------------------------
  // `tools/` holds the validation implementations and the manifest itself. A
  // change here must not be able to narrow what validates it.
  { test: /^tools\//, verdict: { kind: "domain", domain: "validation" } },
  // package.json holds the scripts the runner dispatches to; a change there can
  // silently unbind a check, so it routes like a validation change.
  { test: /^(package\.json|pnpm-lock\.yaml|pnpm-workspace\.yaml|tsconfig.*\.json)$/, verdict: { kind: "domain", domain: "validation" } },
  // Frozen regression baselines. Editing them is prohibited; if it happens
  // anyway, the widest possible validation is the right response.
  { test: /^legacy\//, verdict: { kind: "domain", domain: "validation" } },
  { test: /^\.github\//, verdict: { kind: "domain", domain: "ci" } },

  // --- Product packages ----------------------------------------------------
  { test: /^packages\/contracts\//, verdict: { kind: "domain", domain: "contracts" } },
  { test: /^packages\/sim-core\//, verdict: { kind: "domain", domain: "sim-core" } },
  { test: /^packages\/sim-analysis\//, verdict: { kind: "domain", domain: "sim-analysis" } },
  { test: /^packages\/sim-decisions\//, verdict: { kind: "domain", domain: "sim-decisions" } },
  { test: /^packages\/sim-runtime\//, verdict: { kind: "domain", domain: "sim-runtime" } },
  { test: /^packages\/phenotype\//, verdict: { kind: "domain", domain: "phenotype" } },

  // --- Application ---------------------------------------------------------
  { test: /^apps\/explorer\/android\//, verdict: { kind: "domain", domain: "android" } },
  { test: /^apps\/explorer\//, verdict: { kind: "domain", domain: "explorer" } },
  { test: /^apps\//, verdict: { kind: "domain", domain: "explorer" } },

  // --- Retained scientific evidence ----------------------------------------
  // Not generated output: hand-editing a survey result is a provenance change,
  // so it is treated as a validation concern.
  { test: /^testdata\//, verdict: { kind: "domain", domain: "validation" } },

  // --- Documentation --------------------------------------------------------
  { test: /\.md$/i, verdict: { kind: "domain", domain: "docs" } },
  { test: /^(docs|README)/, verdict: { kind: "domain", domain: "docs" } },
];

/** Classify one changed path. */
export function classifyPath(rawPath: string): PathVerdict {
  const path = clean(rawPath);
  if (path === "") return { kind: "unknown" };
  for (const rule of RULES) {
    if (rule.test.test(path)) return rule.verdict;
  }
  return { kind: "unknown" };
}

// --- Impact planning ---------------------------------------------------------

export interface ImpactPlan {
  /** Domains implied by the change. */
  readonly domains: readonly string[];
  /** True when at least one path could not be classified. Forces everything. */
  readonly unknown: boolean;
  /** Unit ids the change requires. Empty when only generated files changed. */
  readonly unitIds: readonly string[];
  /** One line per changed path, for the CI summary. */
  readonly reasons: readonly string[];
}

export interface ImpactInput {
  /** Units carry their own `domains`; supplied here to keep this module pure. */
  readonly units: ReadonlyArray<{ id: string; domains: readonly string[] }>;
  readonly paths: readonly string[];
}

/**
 * Resolve a diff into the set of units it requires.
 *
 * The unit list is derived by inverting the `domains` recorded on each unit in
 * the manifest, so this function holds no second copy of the mapping. A unit
 * that lists no relevant domain is simply not selected; that is the safe
 * direction, because a unit with a narrow list runs more often, not less.
 */
export function planImpact({ units, paths }: ImpactInput): ImpactPlan {
  const domains = new Set<string>();
  const reasons: string[] = [];
  let unknown = false;

  for (const raw of paths) {
    const verdict = classifyPath(raw);
    switch (verdict.kind) {
      case "generated":
        reasons.push(`${raw} -> generated output (skipped)`);
        break;
      case "domain":
        domains.add(verdict.domain);
        reasons.push(`${raw} -> ${verdict.domain}`);
        break;
      case "unknown":
        unknown = true;
        reasons.push(`${raw} -> unclassified (forces all validation)`);
        break;
    }
  }

  if (unknown) {
    return {
      domains: [...domains].sort(),
      unknown: true,
      // Paused units stay paused even when the change cannot be classified.
      // "Unknown means more validation" must not revive a lane on pause, or
      // the pause would hold everywhere except the broadest diffs -- exactly
      // where an unreliable lane does the most damage.
      unitIds: units.filter((u) => !u.paused).map((u) => u.id),
      reasons,
    };
  }

  // A paused unit is invisible to the runner sets, not merely skipped at
  // runtime: no diff, however broad, may require it. Re-entry re-adds it here
  // by dropping the flag, not by touching this filter.
  const unitIds = units
    .filter((u) => !u.paused && u.domains.some((d) => domains.has(d)))
    .map((u) => u.id);

  return { domains: [...domains].sort(), unknown: false, unitIds, reasons };
}
